import { WxColorStylesStrict } from '../utils/wxtools';

export const __colorStyles_default_preset: WxColorStylesStrict = {
	base: {
		parent: undefined,
		name: 'base',
		fill: 'gradient',
		isolineColor: 'none',
		isolineText: true,
		isolineTextSizeEm: 1.1,
		isolineTextBackground: false,
		vectorType: 'arrows',
		vectorColor: 'inverted',
		vectorFactor: 1,
		streamLineColor: 'none',
		streamLineSpeedFactor: 1,
		streamLineStatic: false,
		showBelowMin: true,
		showAboveMax: true,
		colorScheme: 'diverging_blue_red',
		colors: undefined,
		colorMap: undefined,
		levels: undefined,
		blurRadius: 0,
		addDegrees: 0,
		units: '',
		extraUnits: undefined,
		mask: 'none',
		gl: {
			animationIntensity: 5,
			animationSpeed: 1,
			noiseTexturePow: 5,
			vectorFieldFactor: 1,
			wavesCount: 4,
		},
	},
	custom: {
		parent: undefined,
		name: 'custom',
		fill: 'gradient',
		isolineColor: 'inverted',
		isolineText: true,
		isolineTextSizeEm: 1.1,
		isolineTextBackground: false,
		vectorType: 'arrows',
		vectorColor: 'inverted',
		vectorFactor: 1,
		streamLineColor: '#777',
		streamLineSpeedFactor: 1,
		streamLineStatic: false,
		showBelowMin: true,
		showAboveMax: true,
		colorScheme: 'rainbow',
		colors: undefined,
		colorMap: undefined,
		levels: undefined,
		blurRadius: 0,
		addDegrees: 0,
		units: '',
		extraUnits: undefined,
		mask: 'none',
	},
};
